---
- name: Restart Prometheus
  containers.podman.podman_container:
    name: prometheus
    state: stopped

- name: Start Prometheus
  containers.podman.podman_container:
    name: prometheus
    state: started

